# Generated by Django 5.1.3 on 2024-11-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
